# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sed -i "s/YOUR KEY HERE/$(AppKey)/g" src/applicationInsights.config.json

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: CopyFiles@2
  inputs:
    Contents: '$(Build.SourcesDirectory)/public/**'
    TargetFolder: '$(Build.SourcesDirectory)/spdoctool/website'

- task: CopyFiles@2
  inputs:
    Contents: '$(Build.SourcesDirectory)/Dockerfile'
    TargetFolder: '$(Build.SourcesDirectory)/spdoctool'

- task: CopyFiles@2
  inputs:
    Contents: '$(Build.SourcesDirectory)/default.conf'
    TargetFolder: '$(Build.SourcesDirectory)/spdoctool'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'spdoctool'
    ArtifactName: 'spdoctool'
    publishLocation: 'Container'
